import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="min-h-screen max-w-full bg-gray-900">
					<div className="container mx-auto">{children}</div>
				</div>
			</body>
		</html>
	);
}
